export const ACTION = {
  GETDATA: 'GET_DATA',
  ADDDATA: 'ADD_DATA',
  DELETEDATA: 'DELETE_DATA',
  UPDATEDATA: 'UPDATE_DATA',
  SETLOADING: 'SET_LOADING',
  SETSEARCH: 'GET_SEARCH_DATA',
  SEARCHQUERY: 'GET_SEARCH_QUERY',
  SETTOTALPAGES: 'GET_TOTAL_PAGES',
  SETCURRENTPAGE: 'GET_CURRENT_PAGE',
  SETERROR: 'GET_ERROR',
};
